version: '3'

services:

  api:
    container_name: reiport-backend
    image: reiport-backend-img
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    volumes:
      - myapi:/usr/src/app
    depends_on:
      - reiport-redis
      - reiport_db
    networks:
      - app-network

  reiport-redis:
    container_name: reiport-redis
    image: redis/redis-stack:latest
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - app-network

  reiport_db:
    container_name: reiport_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database/dataBase.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app-network

  reiport_db_interface:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
  myapi:


networks:
  app-network:
    driver: bridge
