server:
  port: 7000
domain:
  name: reiport-entreprise.trl
redis:
  host: 0.0.0.0
  port: 6379
jwt:
  secret: supersecret
spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 25
    username: 7f6b1bdb601444
    password: 48612a2a50c119
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/reiport
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show-sql: true