server:
  port: 3000
redis:
  host: reiport-redis
  port: 6379
jwt:
  secret: supersecret
spring:
  mail:
    host: 
    port: 
    username: 
    password: 
  datasource:
    url: jdbc:postgresql://reiport_db:5432/reiport
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show-sql: true